let promise = new Promise((resolve, reject) => {
    reject(5)
})

promise
.then((val) => console.log(val))
.catch((err) => console.log(err))